<?php

/**
 * @file
 * Contains wsdata.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function wsdata_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wsdata module.
    case 'help.page.wsdata':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Web service data sources as configuration.') . '</p>';
      return $output;

    default:
  }
}
