<?php

function ws_performance_config_form($form, &$form_state) {

  return $form;
}

function ws_performance_config_form_submit($form, &$form_state) {

}

function ws_performance_overview() {
  $form = array();

  return $form;
}

function ws_performance_report($wsconfig) {
  $form = array();

  return $form;
}

function ws_performance_specific_report($wsconfig, $event) {
  $form = array();

  return $form;
}
