wsdata_field.wsfield_config.*:
  type: config_entity
  label: 'Web Service Field config'
  mapping:
    id:
      type: string
      label: 'ID'
    uuid:
      type: string
    wscall:
      label: 'WS Call'
      type: string
    replacements:
      label: 'Replacements'
      type: struct
    returnToken:
      label: 'Return Token'
      type: string
    data:
      label: 'Data'
      type: string
