<?php

/**
 * @file
 * Add support for addressfield to be used with web service fields
 *
 * @author Mathew Winstone <mwinstone@coldfrontlabs.ca>
 */

/**
 * Implements hook_wsfields_FIELD_TYPE_data_alter().
 */
function ws_entityreference_wsfields_entityreference_data_alter($data, $instance) {
  $field = array();
  if (!is_array($data)) {
    $field[LANGUAGE_NONE][] = array('target_id' => $data);
  } else {
    foreach($data as $d) {
      $field[LANGUAGE_NONE][] = array('target_id' => $d);
    }
  }
  return $field;
}
